name: node1
processes:
  -
      name: process1
      cmd: sh /Users/zhouff/gopath/src/github.com/ejunjsh/gopervisor/test.sh
      env:
        env1: env1
      std:
        outfile: /Users/zhouff/process1.log
        errfile: /Users/zhouff/process1.log
      startsecs: 1
      autostart: true
  -
      name: process2
      cmd: sh /Users/zhouff/gopath/src/github.com/ejunjsh/gopervisor/test.sh
      env:
         env1: env1
      std:
          outfile: /Users/zhouff/process2.log
          errfile: /Users/zhouff/process2.log
      startsecs: 2
      autostart: true